version: '3.7'

services:

  metalikha:
    build: .
    #command: gunicorn metalikha.wsgi:application --bind 0.0.0.0:8001
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/usr/src/app/
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on: 
      - metalikha-db
    networks:
      - metalikha-network

  metalikha-db:
    build: ./database
    command: mysqld --default-authentication-plugin=mysql_native_password
    expose:
      - 3306
    #volumes:
    #  - ./database/backup:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=django_secret_pass
      - MYSQL_DATABASE=django_db
      - MYSQL_USER=django_user
      - MYSQL_PASSWORD=django_password
    networks:
      - metalikha-network

  metalikha-db-test:
    build: ./database
    command: mysqld --default-authentication-plugin=mysql_native_password
    expose:
      - 3307
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=django_secret_pass
      - MYSQL_DATABASE=django_db_test
      - MYSQL_USER=django_user_test
      - MYSQL_PASSWORD=django_password_test
    networks:
      - metalikha-network

networks:
  metalikha-network:
    driver: bridge
