# Generated by Django 3.1.7 on 2022-06-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Empresa', max_length=255)),
                ('contact', models.CharField(help_text='Contacto', max_length=255)),
                ('date', models.CharField(help_text='Fecha', max_length=255)),
                ('city', models.CharField(help_text='Ciudad', max_length=255)),
                ('phonenumber', models.CharField(help_text='Telefono', max_length=255)),
                ('address', models.CharField(help_text='Direccion', max_length=255)),
                ('email', models.CharField(help_text='Correo', max_length=255)),
                ('iva', models.CharField(help_text='IVA', max_length=255)),
                ('payment_type', models.CharField(help_text='Tipo de pago', max_length=255)),
            ],
        ),
    ]
