# Generated by Django 3.1.7 on 2022-06-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Descripcion')),
                ('quantity', models.FloatField(help_text='Cantidad')),
                ('unit', models.TextField(help_text='Descripcion')),
                ('unit_price', models.FloatField(help_text='Cantidad')),
                ('total', models.FloatField(help_text='Cantidad')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='items',
            field=models.ManyToManyField(blank=True, to='documents.QuoteItem'),
        ),
    ]
