# Generated by Django 3.1.7 on 2022-06-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20220615_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='total',
        ),
        migrations.AddField(
            model_name='quote',
            name='commercial_terms',
            field=models.TextField(default=1, help_text='Condiciones Comerciales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='money_type',
            field=models.CharField(choices=[('MXN', 'Peso'), ('DLL', 'Dolar')], default='MXN', help_text='Moneda', max_length=3),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='unit',
            field=models.TextField(help_text='Unidad'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='unit_price',
            field=models.FloatField(help_text='Precio Unitario'),
        ),
    ]
