# Generated by Django 3.1.7 on 2022-06-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20220615_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date',
            field=models.DateField(help_text='Fecha'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='email',
            field=models.EmailField(help_text='Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='quote',
            name='iva',
            field=models.IntegerField(help_text='IVA'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='phonenumber',
            field=models.IntegerField(help_text='Telefono'),
        ),
    ]
