# Generated by Django 3.1.7 on 2022-06-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20220615_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(help_text='Tipo de pago', max_length=255)),
                ('cfdi', models.CharField(help_text='CFDI', max_length=255)),
                ('construction_site', models.CharField(help_text='Obra', max_length=255)),
                ('contact', models.CharField(help_text='Contacto', max_length=255)),
                ('provider', models.CharField(help_text='Proveedor', max_length=255)),
                ('address', models.CharField(help_text='Direccion', max_length=255)),
                ('city', models.CharField(help_text='Ciudad', max_length=255)),
                ('state', models.CharField(help_text='Estado', max_length=255)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('date', models.DateField(help_text='Fecha')),
                ('rfc', models.CharField(help_text='RFC', max_length=255)),
                ('extension', models.IntegerField(help_text='Extension')),
                ('cp', models.IntegerField(help_text='CP')),
                ('phone', models.IntegerField(help_text='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Descripcion')),
                ('quantity', models.FloatField(help_text='Cantidad')),
                ('unit', models.TextField(help_text='Unidad')),
                ('unit_price', models.FloatField(help_text='Precio Unitario')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.purchaseorder')),
            ],
        ),
    ]
