# Generated by Django 3.1.7 on 2022-06-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='phonenumber',
            field=models.BigIntegerField(help_text='Telefono'),
        ),
    ]
